### ISSUE TITLE
[Bug] Same Shirt Designs Again Thanks To Daylight Saving Time 

### ISSUE THREAD

**Issue by UdoKifferbrehl** [jiwidi/DailyQwertee#2]
Hi,
thanks for your awesome Telegram bot.

I hereby inform you about a little bug.
Because of the daylight saving time I got the same shirt designs from yesterday today again.
Do you see my point. If not, please do not hesitate to ask any questions you may have.

Thanks!

**Comment by jiwidi** [comment]
Just fixed it, thanks for the issue report
